### ISSUE TITLE
hage-corpに参加できません。

### ISSUE THREAD

**Issue by S-Hatake** [hage-corp/sql_test#2]
わしさん。はたけです。
どうやったらhage-corpのメンバになれるんでしょうか？
とりあえずコードはゲットできましたので、課題やりまちゅ。

**Comment by washi-Z** [comment]
hage-corpにお誘いしました。承認をおねがいしまちゅ。

**Comment by washi-Z** [comment]
解決したら、本イシューをクローズください。
